language: node_js
node_js: 12.13.0

jdk:
  - oraclejdk8
addons:
  sonarcloud: true
script:
  - npm run cover
  - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=diegopm2000-github -Dsonar.projectKey=CalculatorNodeJS -Dsonar.sources='./app' -X

after_success:
 - npm run coveralls
